version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing QOL utils
          command: |
            apt-get update
            apt-get install -y wget unzip
      - run:
          name: Installing nsis
          command: |
            apt-get update
            apt-get install -y nsis
      - run:
          name: Retrieving master archive
          command: wget https://s3.amazonaws.com/dropbox.s3.ncode.ca/FermeCC/all_mods_download.zip
      - run:
          name: Extracting master archive
          command: |
            mkdir -p mods
            unzip all_mods_download.zip -d mods
      - run:
          name: Debug information
          command: find .

