version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing QOL utils
          command: |
            apt-get update
            apt-get install -y wget unzip
      - run:
          name: Installing nsis
          command: |
            apt-get update
            apt-get install -y nsis
      - run:
          name: Retrieve and extractmaster archive
          command: |
            wget https://s3.amazonaws.com/dropbox.s3.ncode.ca/FermeCC/all_mods_download.zip
            mkdir -p mods
            unzip all_mods_download.zip -d mods
      - run:
          name: Compile installer
          command: |
            makensis installer.nsi
      - run:
          name: AV scan
          command: |
            apt-get update
            apt-get install -y clamav
            clamscan
      - run:
          name: Debug information
          command: find .

