version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing nsis
          command: |
            apt-get update
            apt-get install -y nsis
      - run:
          name: Debug information
          command: find .
